version: '3.9'
services:
  coin-detection:
    image: coin-detection
    container_name: coin-detection
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Madrid
      - MIN_COIN_RADIO=10
      - MAX_COIN_RADIO=400
      - MIN_COIN_DISTANCE=100
      - HOUGH_PARAM_1=100
      - HOUGH_PARAM_2=50
    restart: unless-stopped
    ports:
      - 8002:8002
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
